# Netlify Build & Functions Configuration

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions" # Tells Netlify where our function code lives

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  
# This is the magic for local development. It tells the Vite dev server 
# to proxy requests from "/api" to our local serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200